# Client Build
[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Admin Build  
[context.admin]
  base = "admin"
  command = "npm run build"
  publish = "admin/dist"

[[context.admin.redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
